### ISSUE TITLE
Christmas Eve should not be included in calculations

### ISSUE THREAD

**Issue by dracos** [mrwilson/sopn-publish-date#18]
For e.g. PCCs, SI 2012/1917, Schedule 3, Part 1, section 3(b) excludes Christmas Eve as a day when calculating dates, but the code does not handle this. e.g. an election date of 2019-01-10 should give a SOPN date of 2018-12-11, but currently gives a date of 2018-12-12.

```
============================================================ FAILURES =============================================================
_________________________________________ test_january_date_police_and_crime_commissioner _________________________________________
    def test_january_date_police_and_crime_commissioner():
        publish_date = sopn_publish_date.police_and_crime_commissioner(date(2019, 1, 10))

>       assert publish_date == date(2018, 12, 11)
E       assert datetime.date(2018, 12, 12) == datetime.date(2018, 12, 11)
E         -datetime.date(2018, 12, 12)
E         +datetime.date(2018, 12, 11)

tests/test_sopn_publish_date.py:136: AssertionError
```

It looks like the same applies to all the other ones I've checked as well.

**Comment by mrwilson** [comment]
Thanks for this!

Sorry for the late reply - I missed the notification against this repo. I'll take a look very soon.
