### ISSUE TITLE
Custom exceptions should end with "Error"

### ISSUE THREAD

**Issue by symroe** [mrwilson/sopn-publish-date#4]
As per PEP8:

> Because exceptions should be classes, the class naming convention applies here. > However, you should use the suffix "Error" on your exception names (if the exception actually is an error).

https://www.python.org/dev/peps/pep-0008/#exception-names

Raising this issue, because in https://github.com/DemocracyClub/WhoCanIVoteFor/pull/363/commits/ac2ded78a2d4b04a64d8f543c2eab36badf0d25a#diff-13aff42b348527ef9d7427596a08cd08R5I found it hard to know what `AmbiguousElectionId` was, before realising it was a custom exception.

**Comment by mrwilson** [comment]
Thanks @symroe - for some reason I've stopped getting messages from GitHub about new issues, will resolve this soon.
